
baseURL: http://rusticus.io/
languageCode: en-us
title: risticus.io

theme: rusticus

taxonomies:
  category: categories
  tag: tags
  information: information

params:

  title: Rust Community Stuttgart
